"""empty message

Revision ID: b8915baabdfa
Revises: 
Create Date: 2018-12-04 21:08:02.430304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8915baabdfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Todos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Todos_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('task', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'Todos_pkey')
    )
    op.drop_table('todo')
    # ### end Alembic commands ###
